"""Initial schema

Revision ID: 20ca47d23a5d
Revises: 
Create Date: 2025-12-11 13:12:05.118916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ca47d23a5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('juniors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.String(length=7), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('programming_exp_before_uni', sa.String(length=10), nullable=False),
    sa.Column('internship_experience', sa.Text(), nullable=True),
    sa.Column('interest_areas', sa.Text(), nullable=False),
    sa.Column('consultation_category', sa.String(length=50), nullable=False),
    sa.Column('research_phase', sa.Text(), nullable=True),
    sa.Column('job_search_area', sa.Text(), nullable=True),
    sa.Column('consultation_title', sa.String(length=200), nullable=False),
    sa.Column('consultation_content', sa.Text(), nullable=False),
    sa.Column('consent_flag', sa.Boolean(), nullable=False),
    sa.Column('is_matched', sa.Boolean(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("email LIKE '%@stu.musashino-u.ac.jp'", name='check_junior_email_format'),
    sa.CheckConstraint("grade IN ('学部1年', '学部2年', '学部3年', '学部4年', '修士1年', '修士2年')", name='check_junior_grade'),
    sa.CheckConstraint("programming_exp_before_uni IN ('なし', 'あり')", name='check_junior_programming_exp'),
    sa.CheckConstraint('LENGTH(student_id) = 7', name='check_junior_student_id_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_juniors_consultation_category', 'juniors', ['consultation_category'], unique=False)
    op.create_index('idx_juniors_created_at', 'juniors', ['created_at'], unique=False)
    op.create_index(op.f('ix_juniors_is_matched'), 'juniors', ['is_matched'], unique=False)
    op.create_index(op.f('ix_juniors_student_id'), 'juniors', ['student_id'], unique=True)
    op.create_table('seniors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.String(length=7), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('internship_experience', sa.Text(), nullable=True),
    sa.Column('hackathon_experience', sa.String(length=20), nullable=True),
    sa.Column('job_search_completed', sa.String(length=10), nullable=False),
    sa.Column('paper_presentation_exp', sa.String(length=50), nullable=True),
    sa.Column('interest_areas', sa.Text(), nullable=False),
    sa.Column('consultation_categories', sa.Text(), nullable=False),
    sa.Column('research_phases', sa.Text(), nullable=False),
    sa.Column('availability_status', sa.Integer(), nullable=False),
    sa.Column('availability_start_date', sa.Date(), nullable=True),
    sa.Column('availability_end_date', sa.Date(), nullable=True),
    sa.Column('consent_flag', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=50), nullable=True),
    sa.Column('is_graduate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("grade IN ('学部1年', '学部2年', '学部3年', '学部4年', '修士1年', '修士2年')", name='check_senior_grade'),
    sa.CheckConstraint("job_search_completed IN ('まだ', '完了済')", name='check_senior_job_search_completed'),
    sa.CheckConstraint('LENGTH(student_id) = 7', name='check_senior_student_id_length'),
    sa.CheckConstraint('availability_start_date IS NULL OR availability_end_date IS NULL OR availability_start_date <= availability_end_date', name='check_senior_availability_date_range'),
    sa.CheckConstraint('availability_status BETWEEN 0 AND 2', name='check_senior_availability_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seniors_availability_status'), 'seniors', ['availability_status'], unique=False)
    op.create_index(op.f('ix_seniors_is_active'), 'seniors', ['is_active'], unique=False)
    op.create_index(op.f('ix_seniors_is_graduate'), 'seniors', ['is_graduate'], unique=False)
    op.create_index(op.f('ix_seniors_student_id'), 'seniors', ['student_id'], unique=True)
    op.create_table('matchings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matching_score', sa.Float(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_sent_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_content', sa.Text(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('slack_message_ts', sa.String(length=50), nullable=True),
    sa.Column('slack_thread_ts', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'completed', 'cancelled')", name='check_matching_status'),
    sa.CheckConstraint('feedback_rating IS NULL OR (feedback_rating BETWEEN 1 AND 5)', name='check_matching_feedback_rating'),
    sa.ForeignKeyConstraint(['junior_id'], ['juniors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchings_feedback_sent_at'), 'matchings', ['feedback_sent_at'], unique=False)
    op.create_index(op.f('ix_matchings_junior_id'), 'matchings', ['junior_id'], unique=False)
    op.create_index(op.f('ix_matchings_matched_at'), 'matchings', ['matched_at'], unique=False)
    op.create_index(op.f('ix_matchings_senior_id'), 'matchings', ['senior_id'], unique=False)
    op.create_index(op.f('ix_matchings_status'), 'matchings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matchings_status'), table_name='matchings')
    op.drop_index(op.f('ix_matchings_senior_id'), table_name='matchings')
    op.drop_index(op.f('ix_matchings_matched_at'), table_name='matchings')
    op.drop_index(op.f('ix_matchings_junior_id'), table_name='matchings')
    op.drop_index(op.f('ix_matchings_feedback_sent_at'), table_name='matchings')
    op.drop_table('matchings')
    op.drop_index(op.f('ix_seniors_student_id'), table_name='seniors')
    op.drop_index(op.f('ix_seniors_is_graduate'), table_name='seniors')
    op.drop_index(op.f('ix_seniors_is_active'), table_name='seniors')
    op.drop_index(op.f('ix_seniors_availability_status'), table_name='seniors')
    op.drop_table('seniors')
    op.drop_index(op.f('ix_juniors_student_id'), table_name='juniors')
    op.drop_index(op.f('ix_juniors_is_matched'), table_name='juniors')
    op.drop_index('idx_juniors_created_at', table_name='juniors')
    op.drop_index('idx_juniors_consultation_category', table_name='juniors')
    op.drop_table('juniors')
    # ### end Alembic commands ###
